server:
  port: 8010
      
spring:    
  datasource:
    url: jdbc:mysql://sun-spot-analyser-mysql:3306/sunspotanalyser?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

logging:
  config: config/logback-spring.xml
   
app:
  login:
    success-url: http://localhost:3000
    failure-url: http://localhost:3000/login?error